config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :crypto_currencies

  root 'crypto_currencies#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/crypto_currency.rb
class CryptoCurrency < ApplicationRecord

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, :lockable, :timeoutable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :set_common_instance_value

  private

  def set_common_instance_value
    @current_user = current_user

  end
end

app/controllers/crypto_currencies_controller.rb
class CryptoCurrenciesController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/crypto_currencies/index.html.slim
h1 ようこそ
p トップページです。

app/views/crypto_currencies/show.html.slim
h1
  | こんにちは、#{current_user.username}さん
p ユーザー用ページです。

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | CryptoCurrencyTrace
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    nav
      .nav-wrapper
        a.brand-logo.center href="#!"
          = "Rails Matelialize Sample"
        ul.left.hide-on-med-and-down
          - if user_signed_in?
            li
              = link_to 'ウォレットアドレス登録', crypto_currencies_path

          - else
            li
              = link_to 'アカウント登録', new_user_registration_path

        - if user_signed_in?
          ul.right.hide-on-med-and-down
            li
              a.dropdown-trigger data-target="dropdown-setting" href="#!"
                | 設定
                i.material-icons.right arrow_drop_down
          ul#dropdown-setting.dropdown-content
            li
              = link_to 'プロフィール変更', edit_user_registration_path
            li.divider
            li
              = link_to 'ログイン', new_user_session_path

    .container
      - if notice
        p.notice= notice
      - elsif alert
        p.alert= alert
      = yield